Control_empleados/Control_empleados/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    #include urls app.departamentos
    re_path('', include('apps.departamentos.urls')),
    #inlcude urls app.personas
    re_path('', include('apps.personas.urls')),
    
    re_path('', include('apps.home.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Control_empleados/apps/departamentos/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'departament_app'

urlpatterns = [

    path(
        'success/',
        views.Success_View.as_view(), 
        name='success',
        ),
    path(
        'departaments-list',
        views.departament_ListView.as_view(),
        name = "departament_list",
    ),
    path(
        'nuevo_departamento/',
        views.New_departament_view.as_view(),
        name='New_departament',
        ),
]

Control_empleados/apps/personas/urls.py
from django.contrib import admin
from django.urls import path

from . import views
app_name = "person_app"

urlpatterns = [

    path(
        '',
        views.home_view.as_view(),
        name = 'index'
        ),
    path(
        'all-employeed-list/',
    views.ListAllEmploys.as_view(),
    name = 'all_persons',
    ),
    path(
        'people_for_area/<shortname>/',
        views.ListbyArea.as_view(),
        name = 'departament-people'
        ),
    path('buscarempleado/', views.listEmployskeywords.as_view()),
    path('listarhabilidades/', views.skillEmployees.as_view()),
    path(
        'see_employeed/<pk>/',
        views.Employeed_DetailView.as_view(),
        name = 'detail_employeed'        
        ),
    path(
        'AgregarEmpleado/',
        views.Employeed_CreateView.as_view(),
        name = "register_new_employeed"
        ),
    
    path(
        'Hecho/',
        views.successView.as_view(), 
        name = 'Exito'
    ),
    path(
        'update/<pk>/',
        views.employeed_UpdateView.as_view(), 
        name = 'update_employeed',
    ),
     path(
        'BorrarEmpleado/<pk>/',
        views.Employeed_DeleteView.as_view(), 
        name = 'delete_employeed',
    ),
    path(
        'admin-employs/',
        views.Admin_Employs_listView.as_view(), 
        name = 'Admin_Employs',
    ),


]

Control_empleados/templates/includes/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <title>{% block title %} {% endblock title %}</title>

</head>
<body>

{% block content %} {% endblock content %}

    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.min.js' %}"></script>
    <script>
      $(document).foundation();
    </script>
</body>

</html>

Control_empleados/templates/includes/header.html
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Empleados</li>
      <li><a href="{% url 'person_app:all_persons' %}">Listar</a></li>
      <li><a href="{% url 'departament_app:departament_list' %}">Departamentos</a></li>
      <li><a href="{% url 'person_app:Admin_Employs' %}">Administrar</a></li>
      <li><a href="{% url 'departament_app:New_departament' %}">Registrar Departamentos</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Buscar Empleado"></li>
      <a class="button primary" href="{% url 'person_app:register_new_employeed' %}">Registrar Nuevo</a>
    </ul>
  </div>
</div>

Control_empleados/templates/includes/success.html
{% extends 'includes/base.html' %}
{% load static %}
{% block title %}
Realizado
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <div class="callout primary grid-x grid-padding-x align-center margin-vertical-2">
                <h1>Operacion Realizada Con Exito</h1>
            </div>
            <img src="{% static 'img/index.png' %}" alt="Spike de cowboy beebop">

        </div>
    </div>

{% endblock content %}