Control_empleados/Control_empleados/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    #include urls app.departamentos
    re_path('', include('apps.departamentos.urls')),
    #inlcude urls app.personas
    re_path('', include('apps.personas.urls')),
    
    re_path('', include('apps.home.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Control_empleados/apps/personas/urls.py
from django.contrib import admin
from django.urls import path

from . import views
app_name = "person_app"

urlpatterns = [

    path(
        '',
        views.home_view.as_view(),
        name = 'index'
        ),
    path(
        'all-employeed-list/',
    views.ListAllEmploys.as_view(),
    name = 'all_persons',
    ),
    path(
        'people_for_area/<shortname>/',
        views.ListbyArea.as_view(),
        name = 'departament-people'
        ),
    path('buscarempleado/', views.listEmployskeywords.as_view()),
    path('listarhabilidades/', views.skillEmployees.as_view()),
    path(
        'see_employeed/<pk>/',
        views.Employeed_DetailView.as_view(),
        name = 'detail_employeed'        
        ),
    path(
        'AgregarEmpleado/',
        views.Employeed_CreateView.as_view(),
        name = "register_new_employeed"
        ),
    
    path(
        'Hecho/',
        views.successView.as_view(), 
        name = 'Exito'
    ),
    path(
        'update/<pk>/',
        views.employeed_UpdateView.as_view(), 
        name = 'update_employeed',
    ),
     path(
        'BorrarEmpleado/<pk>/',
        views.Employeed_DeleteView.as_view(), 
        name = 'delete_employeed',
    ),
    path(
        'admin-employs/',
        views.Admin_Employs_listView.as_view(), 
        name = 'Admin_Employs',
    ),


]

Control_empleados/apps/personas/models.py
from django.db import models
from apps.departamentos.models import Departament

class Skill(models.Model):
    name = models.CharField(("Habilidades"), max_length=50, null = True)

    class Meta:
        verbose_name = ("Habilidad")
        verbose_name_plural = ("Habilidades")

    def __str__(self):
        return "{} - {}".format(self.id, self.name)


class Empleado(models.Model):
    """modelo para la tabla empelado"""
    first_name = models.CharField(("Nombres"), max_length=75)
    last_name = models.CharField(("Apellidos"), max_length=75)
    full_name = models.CharField(
        ("Nombres Completos"),
         max_length=150,
         blank=True,
         )
    job = models.CharField(("Trabajo"), max_length=1, choices=(
         ('0', 'Modelista'),
         ('1', 'Developer_Backend'),
         ('2', 'Developer_Javascript'),
         ('3', 'Tester_developer'),
         ('4', 'contador@'),
         ('5', 'Administradora'),
         ('6', 'Tecnico de redes'),
         ))
    departament = models.ForeignKey(Departament, on_delete=models.CASCADE)
    avatar = models.ImageField(("Imagen de referencia"), upload_to='empleado', blank = True, null = True)
    skills = models.ManyToManyField(Skill)

    
    class Meta:
        verbose_name = "Empleado"
        verbose_name_plural = "Empleados"
        ordering = ['job']

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)
    
        

Control_empleados/templates/person/Admin_employs.html
{% extends 'includes/base.html' %}

{% block title %}
Administrador
{% endblock title %}
    
{% block content %}
    
    {% include 'includes/header.html' %}
   <div class="grid-container">
       <div class="grid-x">
            <h1 class="cell">Lista empleados</h1>
            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">Id</th>
                        <th>Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">Departamentos</th>
                        <th width="200">Accion</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for li in employs  %} 
                            <tr>
                                <td>{{li.id}}</td>
                                <td>{{li.first_name}}.</td>
                                <td>{{li.last_name}}</td>
                                <td>{{li.departament}}</td>
                                <td><a class="button Success" href="{% url 'person_app:update_employeed' li.id %}">Editar</a>
                                <a class="button Alert" href="{% url 'person_app:delete_employeed' li.id %}">Eliminar</a></td>
                            </tr>
                        {% endfor %}    
                    </tbody>
                  </table>
            </div>
            <div class="cell">
                {% if is_paginated %}
                    <nav aria-label="Pagination">
                        <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="pagination-previous">
                            <a href="?page={{page_obj.previous_page_number}}"> Atras </a>
                            </li>
                        {% endif %}

                        {% for page in paginator.page_range %}
                            {% ifequal page page_obj.number %}
                                <li class="current"><span class="show-for-sr">Pagina actual</span> {{page}}</li>
                            {% else %}
                                <li><a href="?page={{page}}" aria-label="Page">{{page}}</a></li>
                            {% endifequal %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Siguiente <span class="show-for-sr">Pagina</span></a></li>
                        {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
       </div>

    <h1> listando a todos los empelados </h1>
   
{% endblock content %}

Control_empleados/templates/person/add_employeed.html
{% extends 'includes/base.html' %}

{% block title %}
    Regisrar empleado
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
                <h1 class="cell">Agregar empleado</h1>
                <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <!-- enctype="multipart/form-data" ESTE PARAMETRO ES PARA PODER SUBIR IMAGENES DESDE UNA VISTA -->
                     <div class="cell">
                        <label>Nombres: 
                            {{form.first_name}}
                       </label> 
                        <label>Apellidos
                            {{form.last_name}}
                        </label>
                        <label>Trabajo:
                            {{form.job}}
                        </label>
                        <label>Departamento:
                            {{form.departament}}
                        </label>
                        <label>Foto:
                            {{form.avatar}}
                        </label>
                        <label>Habilidades:
                            {{form.skills}}
                        </label>
                         
                     </div>

                <div class="large-5 columns large-offset-5">
                    <button type="submit" class="button">Agregar</button>
                </div>
                </form>

        </div>
    </div>
     
{% endblock content %}

   

Control_empleados/templates/person/byarea.html
{% extends 'includes/base.html' %}
{% block title %}
Empleados por area
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}
    
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">
                <h1 style="text-align: center;"> Empleados</h1>
                <div class="cell">
                    <table>
                    <thead>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Apellidos</th>
                        <th>Departamento</th>
                    </thead>
                        <tbody>
                            {% for employees in Employeed %}
                                <tr>
                                    <td>{{employees.id}}</td>
                                    <td>{{employees.first_name}}</td>
                                    <td>{{employees.last_name}}</td>
                                    <td>{{employees.departament}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
           

        </div>
    </div>

{% endblock content %}
    

Control_empleados/templates/person/delete_employeed.html
{% extends 'includes/base.html' %}

{% block title %}
Eliminar empleado
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}
    <div style="background-color: black;">
    <div class="grid-container">
        <div class="grid-x">
                <h1 class="cell" style="color: white;">Confirme que desea eliminar el registro del empleado {{Employeed.first_name}} {{Employeed.last_name}}</h1>

                <form class="cell" method="POST">{% csrf_token %}
                    <div class="callout alert">
                        <h5>Desea Eliminarlo?</h5>
                        <button type="submit" class="alert button">Confirme Eliminacion</button>
                    </div>
                    <p style="color: yellow;">Los datos borrados no podran ser recuperados</p>
                </form>
            </div>
        </div>
    </div>
    </div>

{% endblock content %}

Control_empleados/templates/person/detail_empleado.html
{% extends 'includes/base.html' %}
{% load static %}

{% block title %} 
Detalle de un empleado
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="callout grid-x grid-padding-x align-center">
        
        <div class="cell small-5">
            <div class="card" style="width: 500px;">
                <div class="card-divider">
                  <h1>{{empleado.first_name}} {{empleado.last_name}}</h1>  
                </div>
                 {% if empleado.avatar%}
                    <img src="{{empleado.avatar.url}}"  style="width: 500px; height: 450px;">
                {% else %}
                    <img src="{% static 'img/MOB.jpeg' %}" style="width: 500px; height: 450px;">
                {% endif %}
                <div class="card-section">
                   <h3> {{empleado.departament}} </h3>
                  <h4><p>{{empleado.get_job_display}}</p></h4>
                </div>
              </div>
        </div>
    </div>
    
    <ul class="accordion" data-accordion data-allow-all-closed="true">
        <li class="accordion-item is-active" data-accordion-item>
            <h2>
                <a href="#" class="accordion-title">Lista de habilidades</a>
            </h2>
        {% comment %} {% for li in skills%}
          <div class="accordion-content" data-tab-content>
              <p>{{li}}</p>
            </div>
            {% endfor %}
        </li>  get across the context more info in view {% endcomment %} 
        
        {% for li in empleado.skills.all%}
          <div class="accordion-content" data-tab-content>
              <p>{{li.name}}</p>
            </div>
            {% endfor %}
        </li>
        <!-- ... -->
      </ul>

    
</div>
{% endblock content %}

Control_empleados/templates/person/keyword.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>HOLA POR PALABRA EN CAJA DE TEXTO</h1>

    <form method="GET">{% csrf_token %}
        <input type="text" id="kword" name="kword" placeholder="Ingrese nombre aqui">
        <button type="submit">  BUSCAR</button>
    </form>

<ul>
    <h1>
        RESULTADOS
    </h1>

    
    {% for employes in employees %}
    <li>
        {{employes}}
    </li>
    {% endfor %}
</ul>
</body>
</html>

Control_empleados/templates/person/list_all_employees.html
{% extends 'includes/base.html' %}

    
{% block content %}
    
    {% include 'includes/header.html' %}
   <div class="grid-container">
       <div class="grid-x">
            <h1 class="cell">Lista empleados</h1>
            <div class="cell grid-x grid-margin-x">
                <div class="cell large-7">
                    <form action="" method="GET">{% csrf_token %}
                        <input type="text" id="kword" name="kword" placeholder="Buscar Empleado">
                </div>
                <div class="cell large-2">
                        <button type="submit" class="success button">Buscar</button>
                    </form>   
                </div>
            </div>
            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">Id</th>
                        <th>Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">Departamentos</th>
                        <th width="150">Accion</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for li in list  %} 
                            <tr>
                                <td>{{li.id}}</td>
                                <td>{{li.first_name}}.</td>
                                <td>{{li.last_name}}</td>
                                <td>{{li.departament}}</td>
                                <td><a class="button warning" href="{% url 'person_app:detail_employeed' li.id %}">Ver</a></td>
                            </tr>
                        {% endfor %}    
                    </tbody>
                  </table>
            </div>
            <div class="cell">
                {% if is_paginated %}
                    <nav aria-label="Pagination">
                        <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="pagination-previous">
                            <a href="?page={{page_obj.previous_page_number}}"> Atras </a>
                            </li>
                        {% endif %}

                        {% for page in paginator.page_range %}
                            {% ifequal page page_obj.number %}
                                <li class="current"><span class="show-for-sr">Pagina actual</span> {{page}}</li>
                            {% else %}
                                <li><a href="?page={{page}}" aria-label="Page">{{page}}</a></li>
                            {% endifequal %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Siguiente <span class="show-for-sr">Pagina</span></a></li>
                        {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
       </div>

    <h1> listando a todos los empelados </h1>
   
{% endblock content %}

Control_empleados/templates/person/skills.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>LISTAR HABILIDADES</h1>


    <form method="GET">{% csrf_token %}
        <input type="text" id ="pallskills" name="pallskills" placeholder="0">
        <button type="submit">BUSCAR</button>
    
    </form>

     <ul>
        {% for li in skillss %}
            <li>
                {{li}}
            </li>
        {% endfor %}
    </ul> 

</body>
</html>

Control_empleados/templates/person/success.html
{% extends 'includes/base.html' %}
{% load static %}
{% block title %}
Realizado
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <div class="callout primary grid-x grid-padding-x align-center margin-vertical-2">
                <h1>Operacion Realizada Con Exito</h1>
            </div>
            <img src="{% static 'img/index.png' %}" alt="Spike de cowboy beebop">

        </div>
    </div>

{% endblock content %}

Control_empleados/templates/person/update_employeed.html
{% extends 'includes/base.html' %}

{% block title %}
    Actualir Empleado
{% endblock title %}

{% block content %}

    {% include 'includes/header.html' %}


<div class="grid-container">
    <div class="grid-x">
    <div class="cell">
        <h1>Modificar datos de un empleado</h1>
    </div>

        <div class="cell">
            <form method="POST">{% csrf_token %}
                <label>Nombres
                    {{form.first_name}}
                </label>
                <label>Apellidos
                    {{form.last_name}}
                </label>
                <label>Trabajo
                    {{form.job}}
                </label>
                <label>Departamento
                   {{form.departament}}
                </label>
                <label> Habilidades
                {{form.skills}}
                </label>

                <button type="submit" class="button primary">Guardar cambios</button>
            </form>

        </div>
    </div>
</div>
    
{% endblock content %}

    
    