Control_empleados/Control_empleados/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    #include urls app.departamentos
    re_path('', include('apps.departamentos.urls')),
    #inlcude urls app.personas
    re_path('', include('apps.personas.urls')),
    
    re_path('', include('apps.home.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Control_empleados/apps/home/urls.py
from django.contrib import admin
from django.urls import path

# from .views import view_proob, ListView
from . import views #import all class of views.py

app_name = "home_app"

urlpatterns = [
    path('proob/', views.view_proob.as_view()),
    path('lista/', views.PruebaListView.as_view()),
    path('pruebalista', views.Proob_list.as_view()),
    path('home', views.ProobCreateView.as_view(), name='pruebadd'),
    path('foundation',
        views.foundation_view.as_view(),
        name='foundation'
    ),
]

Control_empleados/apps/personas/urls.py
from django.contrib import admin
from django.urls import path

from . import views
app_name = "person_app"

urlpatterns = [

    path(
        '',
        views.home_view.as_view(),
        name = 'index'
        ),
    path(
        'all-employeed-list/',
    views.ListAllEmploys.as_view(),
    name = 'all_persons',
    ),
    path(
        'people_for_area/<shortname>/',
        views.ListbyArea.as_view(),
        name = 'departament-people'
        ),
    path('buscarempleado/', views.listEmployskeywords.as_view()),
    path('listarhabilidades/', views.skillEmployees.as_view()),
    path(
        'see_employeed/<pk>/',
        views.Employeed_DetailView.as_view(),
        name = 'detail_employeed'        
        ),
    path(
        'AgregarEmpleado/',
        views.Employeed_CreateView.as_view(),
        name = "register_new_employeed"
        ),
    
    path(
        'Hecho/',
        views.successView.as_view(), 
        name = 'Exito'
    ),
    path(
        'update/<pk>/',
        views.employeed_UpdateView.as_view(), 
        name = 'update_employeed',
    ),
     path(
        'BorrarEmpleado/<pk>/',
        views.Employeed_DeleteView.as_view(), 
        name = 'delete_employeed',
    ),
    path(
        'admin-employs/',
        views.Admin_Employs_listView.as_view(), 
        name = 'Admin_Employs',
    ),


]

Control_empleados/apps/home/models.py
from django.db import models

# Create your models here.
class Proob(models.Model):
    title = models.CharField(('Titulo'), max_length=50)
    sub_title = models.CharField(('Subtitulo'), max_length=50)
    quanti = models.IntegerField(('Cantidad'))

    class Meta:
        verbose_name = ("Prueba")
        verbose_name_plural = ("Pruebas")

    def __str__(self):
        return ' {} - {}'.format(self.title, self.sub_title)
        

Control_empleados/apps/home/forms.py
from django import forms

from .models import Proob


class ProobForm(forms.ModelForm):
    
    class Meta:
        model = Proob
        fields = [
            'title',
            'sub_title',
            'quanti',
        ]
        widgets = {
            'title':forms.TextInput(
                attrs={
                    'placeholder': 'Ingrese el texto aquí.'
                }
            )
        } 


    def clean_quanti(self):
        data = self.cleaned_data["quanti"]
        if data < 10:
            raise forms.ValidationError("Debe ser mayor a 10")
        return data
    

Control_empleados/apps/home/views.py
from django.shortcuts import render
#
from django.views.generic import (
    TemplateView,
    ListView, 
    CreateView,
    )
from .models import Proob
from .forms import ProobForm

class view_proob(TemplateView):
    template_name = 'home/index.html'

class foundation_view(TemplateView):
    template_name = 'home/foundation.html'

class PruebaListView(ListView):
    # model = Prueba  aca irira un modelo para listar
    template_name = "home/list.html"
    context_object_name = 'num_list'
    queryset = ['0', '1', '2', '3', '4', '5',]


class Proob_list(ListView):
    template_name = "home/list_proob.html"
    model = Proob
    context_object_name = 'list'

class ProobCreateView(CreateView):
    model = Proob
    template_name = "home/home.html"
    # fields = ['title', 'sub_title', 'quanti']
    form_class = ProobForm
    success_url = '/'

Control_empleados/templates/departament/departament_list.html
{% extends 'includes/base.html' %}

{% block title %}
Departamentos
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <div class="cell">
            <h1>Departamentos de la empresa</h1> 
            <div class="cell">
                <table>
                <thead>
                    <th>Nombre Completo</th>
                    <th>Nombre Corto</th>
                    <th>Accion</th>
                </thead>
                    <tbody>
                        {% for departament in departaments %}
                            <tr>
                                <td>{{departament.name}}</td>
                                <td>{{departament.short_name}}</td>
                                <td><a class="button warning" href="{% url 'person_app:departament-people' departament.short_name %}">Ver Empleados</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>

    </div>

</div>

{% endblock content %}

Control_empleados/templates/departament/home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>HOLA HOME</h1>
</body>
</html>

Control_empleados/templates/departament/new_departament.html
{% extends 'includes/base.html' %}
{% block title %}
Registrar Departamento
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container grid">
        <div class="grid-x">
            <div class="cell align-center">
            <h1>Registrar nuevo departamento</h1>

    <div class="cell callout">

        <form class="align-center grid-x grid-margin-x" method="post">{% csrf_token %}
            <div class="medium-5 cell">
                <h4> <p> Empleado </p></h4>
                <label class="cell"> Nombre de Encargado de departamento.
                    {{form.name}}
                </label >
                <label class="cell"> Apellido.
                    {{form.last_name}}
                </label >
            </div>
            <div class="medium-5 cell">
                <h4> <p> Departamento </p></h4>
                <label class="cell"> Nombre del Departamento..
                    {{form.departament}}
                </label >
                <label class="cell"> Nombre corto del departamento.
                    {{form.short_name}}
                </label >
            </div>
        </form>
        <div class="grid-x grid-padding-x align-center"> <!-- Aligned to the center -->
            <button type="submit" class="cell small-2 success button">Guardar</button>
         </div>
          
    </div>
    

            </div>
        </div>
    </div>

    
{% endblock content %}
    

Control_empleados/templates/departament/success.html
{% extends 'includes/base.html' %}
{% load static %}
{% block title %}
Realizado
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="cell" style="height:75px;">

        </div>
        <div class="grid-x grid-margin-y" style="height: 125px;">
            <div class="cell callout primary grid-x align-center">
                <h1>Operacion Realizada Con Exito</h1>
            </div>
        </div>
        
        <div class="grid-x">
            <img class="cell grid-x" src="{% static 'img/zenitsu.webp' %}" alt="Spike de cowboy beebop">
        </div>
    </div>

{% endblock content %}